availableSecrets:
  secretManager:
    - versionName: projects/772190012442/secrets/APPLICATION-CHAT/versions/latest
      env: SECRET_ENV_CHAT

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_CHAT" > src/main/resources/secret.yml
    secretEnv: ['SECRET_ENV_CHAT']

  - name: gradle:7.6-jdk21
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-chat/planpal-chat',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-chat/planpal-chat']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        'compute', 'instances', 'create-with-container',
        'planpal-chat-instance-1',
        '--zone', 'asia-northeast3-a',
        '--container-image', 'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-chat/planpal-chat'
      ]

options:
  logging: CLOUD_LOGGING_ONLY