apiVersion: apps/v1
kind: Deployment
metadata:
  name: planpal-chat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planpal-chat
  template:
    metadata:
      labels:
        app: planpal-chat
    spec:
      containers:
        - name: planpal-chat-container
          image: asia-northeast3-docker.pkg.dev/k8s-test-464207/k8s-server-registry/planpal-chat-server:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: secrets-volume
              mountPath: "/app/resources-chat"
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: planpal-config-secret-chat